name: Run Backend Daily

on:
  schedule:
    - cron: '55 23 * * *'  
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check if database exists
      run: ls -la ./backend/players.db

    - name: Set up C++ environment
      uses: aminya/setup-cpp@v1
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev libcurl4-openssl-dev nlohmann-json3-dev

    - name: Build and run backend
      run: |
        cd backend
        cmake .
        make
        ./backend

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./backend/players.db
        git commit -m "Update database"

    - name: Push changes
      run: git push

